name: ambient_sensors
description: Flutter plugin for accessing the Android and iOS accelerometer, gyroscope, magnetometer, and orientation sensors.
version: 0.1.0
homepage: https://github.com/zesage/ambient_sensors

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: finaldev.ambient_sensors
        pluginClass: AmbientSensorsPlugin
      ios:
        pluginClass: AmbientSensorsPlugin
